#!/usr/bin/env python3
"""Run Chapter 5 wrapper in baseline/optional-LLM mode."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Dict, List, Optional


def _find_workspace_root() -> Path:
    here = Path(__file__).resolve()
    return here.parents[1]


def _read_queries(path: Path) -> List[str]:
    path = path.resolve()
    if not path.exists():
        raise FileNotFoundError(f"query_file not found: {path}")
    if path.suffix.lower() == ".jsonl":
        out: List[str] = []
        with path.open("r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                obj = json.loads(line)
                q = obj.get("query") or obj.get("question")
                if isinstance(q, str) and q.strip():
                    out.append(q.strip())
        return out
    # fallback: plain text, one query per line
    out = []
    for ln in path.read_text(encoding="utf-8").splitlines():
        ln = ln.strip()
        if ln:
            out.append(ln)
    return out


def _load_severity(severity_json_path: Optional[Path], severity_json: Optional[str]) -> Optional[Dict[str, object]]:
    if severity_json_path is None and severity_json is None:
        return None
    if severity_json_path is not None:
        return json.loads(severity_json_path.read_text(encoding="utf-8"))
    assert severity_json is not None
    return json.loads(severity_json)


def parse_args() -> argparse.Namespace:
    root = _find_workspace_root()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--query", type=str, default=None, help="Single query string.")
    parser.add_argument("--query_file", type=Path, default=None, help="Optional .jsonl/.txt with queries.")
    parser.add_argument(
        "--manifest_path",
        type=Path,
        default=root / "results" / "kb_build_latest" / "kb_manifest.json",
        help="Path to kb_manifest.json generated by build_kb.py.",
    )
    parser.add_argument(
        "--kb_index_dir",
        type=Path,
        default=None,
        help="Alternative input: kb_index directory. If set, manifest is assumed at ../kb_manifest.json",
    )
    parser.add_argument("--severity_json_path", type=Path, default=None, help="Optional path to severity JSON.")
    parser.add_argument("--severity_json", type=str, default=None, help="Optional inline severity JSON string.")
    parser.add_argument("--mode", type=str, default="baseline", choices=["baseline", "llm"])
    parser.add_argument("--retrieval_k", type=int, default=5)
    parser.add_argument(
        "--retrieval_backend",
        type=str,
        default=None,
        choices=["keyword", "tfidf", "hybrid"],
        help="Optional backend override. Defaults to manifest backend.",
    )
    parser.add_argument(
        "--disable_rerank",
        action="store_true",
        help="Disable reranker stage (enabled by default).",
    )
    parser.add_argument("--rerank_pool", type=int, default=20, help="Candidate pool size before reranking.")
    parser.add_argument("--rerank_alpha", type=float, default=0.20, help="Blend weight for rerank score.")
    parser.add_argument("--min_top_score_for_answer", type=float, default=0.18)
    parser.add_argument("--min_mean_score_for_answer", type=float, default=0.12)
    parser.add_argument("--min_retrieved_for_answer", type=int, default=2)
    parser.add_argument("--run_id", type=str, default=None)
    parser.add_argument(
        "--out_dir",
        type=Path,
        default=root / "results" / "wrapper_latest",
        help="Output directory for wrapper outputs.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    import sys

    workspace_root = _find_workspace_root()
    if str(workspace_root) not in sys.path:
        sys.path.insert(0, str(workspace_root))

    from pico_wrapper.utils_io import ensure_dir, freeze_environment, generate_run_id, write_json, write_jsonl
    from pico_wrapper.wrapper import run_wrapper

    queries: List[str] = []
    if args.query:
        queries.append(args.query.strip())
    if args.query_file:
        queries.extend(_read_queries(args.query_file))
    queries = [q for q in queries if q]
    if not queries:
        raise ValueError("Provide --query and/or --query_file with at least one query.")

    manifest_path = args.manifest_path.resolve()
    if args.kb_index_dir is not None:
        manifest_path = (args.kb_index_dir.resolve().parent / "kb_manifest.json").resolve()
    if not manifest_path.exists():
        raise FileNotFoundError(f"kb manifest not found: {manifest_path}")

    severity = _load_severity(args.severity_json_path, args.severity_json)
    run_id = args.run_id or generate_run_id("chapter5_wrapper")

    out_dir = ensure_dir(args.out_dir.resolve())
    outputs_path = out_dir / "wrapper_outputs.jsonl"
    infos_path = out_dir / "wrapper_run_infos.jsonl"
    config_path = out_dir / "run_config.json"

    output_rows: List[Dict[str, object]] = []
    info_rows: List[Dict[str, object]] = []
    for q in queries:
        output, info = run_wrapper(
            query=q,
            manifest_path=manifest_path,
            run_id=run_id,
            retrieval_k=args.retrieval_k,
            retrieval_backend=args.retrieval_backend,
            enable_rerank=not args.disable_rerank,
            rerank_pool=args.rerank_pool,
            rerank_alpha=args.rerank_alpha,
            min_top_score_for_answer=args.min_top_score_for_answer,
            min_mean_score_for_answer=args.min_mean_score_for_answer,
            min_retrieved_for_answer=args.min_retrieved_for_answer,
            mode=args.mode,
            severity=severity,
        )
        output_rows.append(output.to_dict())
        info_rows.append(info.to_dict())

    write_jsonl(outputs_path, output_rows)
    write_jsonl(infos_path, info_rows)
    write_json(
        config_path,
        {
            "run_id": run_id,
            "n_queries": len(queries),
            "manifest_path": str(manifest_path),
            "mode_requested": args.mode,
            "retrieval_k": args.retrieval_k,
            "retrieval_backend": args.retrieval_backend,
            "rerank_enabled": (not args.disable_rerank),
            "rerank_pool": args.rerank_pool,
            "rerank_alpha": args.rerank_alpha,
            "min_top_score_for_answer": args.min_top_score_for_answer,
            "min_mean_score_for_answer": args.min_mean_score_for_answer,
            "min_retrieved_for_answer": args.min_retrieved_for_answer,
            "has_severity_context": severity is not None,
            "query_file": None if args.query_file is None else str(args.query_file.resolve()),
        },
    )
    freeze_environment(out_dir / "environment.txt")

    print(f"Wrapper run complete. run_id={run_id}")
    print(f"Queries processed: {len(queries)}")
    print(f"Outputs: {outputs_path}")
    print(f"Run info: {infos_path}")


if __name__ == "__main__":
    main()
